
# set snippet ----
# usethis::edit_rstudio_snippets()
# Ctrl+Shift-P - Show Command Palette
rstudiotools::setcwd()
try( dev.off(dev.list()["RStudioGD"]),silent=T) # Clear Plots
rm(list=ls()) # Clear Workspace
gc()
cat("\014") # Clear Console ctrl+L
xfunctions::XLibrary("howler","minifunctions","rstudiotools","aitools","xfunctions")
# xfunctions::XFunctions("howler")
help(package="howler")
packageDescription("howler")
# devtools::install_github("author_name/howler", build_vignettes = TRUE, dependencies = TRUE)
# browseVignettes(package="howler")
# vignette(package="howler")
# vignette("vignette-name",package="howler")
# https://cranlogs.r-pkg.org/badges/last-month/howler
rstudiotools::showinfo()

usethis::use_git()
#usethis::use_git_remote("origin", url = NULL, overwrite = TRUE)

usethis::use_github()

usethis::use_readme_rmd()

usethis::browse_github()

usethis::use_git_ignore("voices")


# Start LM Studio if needed (if terminal already in use, close terminal panel and run again)
terminal_id = rstudiotools::terminal("./powershell/LMstudioStart.ps1",caption="Claude")
# Start Claude Code if needed
terminal_id = rstudiotools::terminal("claude --model qwen/qwen3.5-9b",terminal_id = terminal_id)

# prompt = "Review the project and update claude.md to reflect the current architecture and recent changes."
# terminal_id = rstudiotools::terminal(prompt, terminal_id = terminal_id)
# terminal_id = rstudiotools::terminal("qual a capital de El Salvador ?", terminal_id = terminal_id)

# Images generated by Google Flow do not store the prompt in the metadata
# f = "P:/DISKD/Wallpapers/A001.jpeg"
# Images generated by ComfyUI do store the prompt in the metadata
# f = "S:/ComfyUI/ComfyUI-Easy-Install/ComfyUI/output/Fantasy/JR_00007_.png"
# img = magick::image_read(f)
# info = magick::image_info(img)
# attrs = magick::image_attributes(img)
# prompt = subset(attrs,property=="prompt",select="value",drop=T)
# prompt_list = jsonlite::fromJSON(prompt)
# prompt = prompt_list[["67"]][["inputs"]][["value"]]
# prompt

# stringr::str_squish all the lines of external file
# lines = readr::read_lines(output_file)
# lines = stringr::str_squish(lines)
# readr::write_lines(lines,output_file)

pak::pak("eduardojacob/rstudiotools")
pak::pak("eduardojacob/aitools")
pak::pak("eduardojacob/xfunctions")
pak::pak("eduardojacob/minifunctions")

pkgbuild::check_build_tools(debug = TRUE)

devtools::install_github("eduardojacob/rstudiotools", build_vignettes = TRUE, dependencies = TRUE)
devtools::install_github("eduardojacob/aitools", build_vignettes = TRUE, dependencies = TRUE)
devtools::install_github("eduardojacob/xfunctions", build_vignettes = TRUE, dependencies = TRUE)
devtools::install_github("eduardojacob/minifunctions", build_vignettes = TRUE, dependencies = TRUE)

minifunctions::imagegrid("P:/DISKD/Youtube R Programming/AppLogos")

rstudiotools::setcwd("./screenshots")
rstudiotools::displaymedia()
rstudiotools::setcwd()

source("ComfyUIfunctions.R")

# Make an inventory of models used in workflows
# Using zeallot package for multiple assignment (unpacking) , aka destructuring assignment in other languages
library("zeallot")
c(workflows,models) %<-% COMFYUI_GET_MODELS()

# rstudiotools::terminal("huggingface-cli login")

# Install models from WSL
# wsl -d Ubuntu
# cd ~
# source ~/hf_env/bin/activate
# hf auth login
# hf download Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign
# (hf_env) eduar@EDUARDO-PC:~$ cp -r ~/.cache/huggingface/hub/models--Qwen--Qwen3-TTS-12Hz-1.7B-VoiceDesign /mnt/s/ComfyUI/ComfyUI-Easy-Install/ComfyUI/models/qwen-tts/
















